//@host = http://localhost:3000

@host = https://api-store-eiuk.onrender.com
@apiProducts = {{host}}/api/products
@apiUsers = {{host}}/api/users

GET {{apiProducts}}

###
GET {{apiProducts}}/671b89453c3445b535fd408d

###
GET {{apiProducts}}/price/2/100

###
GET {{apiProducts}}/actives
###
POST {{apiProducts}}
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjc0ZGNhNGU0ZjJkNDU2NTJmZGFkYjlhIiwiaWF0IjoxNzMzMTUxNDM5fQ.18ppcmV-N8pwnttE0J2My7Mb8bilc1eR2fWkx8M-aHU

{
    "name": "correa de perro",
    "description": "5m de diversion",
    "price": 10,
    "department":"home",
    "stock":130,
    "available":true
}

###
DELETE {{apiProducts}}/674d6f629d98956bf09ae3fc


###
POST {{apiUsers}}/register
Content-Type: application/json

{
     "username": "chenoita",
    "email": "chenoa2001@gmail.com",
    "password": "123456",
    "role": "regular"
}


###
POST {{apiUsers}}/login
Content-Type: application/json

{
    "email": "chenoa2001@gmail.com",
    "password": "123456"
}

###
PUT {{apiUsers}}/add-product/
Authorization: : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjc0ZGNhNGU0ZjJkNDU2NTJmZGFkYjlhIiwiaWF0IjoxNzMzMTUxNDM5fQ.18ppcmV-N8pwnttE0J2My7Mb8bilc1eR2fWkx8M-aHU

